"$schema" = ".schema.json"

[[permission]]
identifier = "allow-ping-scoped"
description = "This enables the ping command with a test scope."
commands.allow = ["ping"]
[permission.scope.allow]
path = "x"
